// resources/js/components/link/SecondaryLink.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3';

type LinkType = {
    href: string;
    addClasses?: string;
    title?: string;
};

const props = defineProps<LinkType>();
</script>

<template>
    <Link
        :href="href"
        :title="title"
        :class="`w-fit rounded border px-2 py-1 font-medium ${addClasses}`"
    >
        <slot />
    </Link>
</template>

// public/js copy 2/components/link/secondary-link.tsx
import { Link } from '@inertiajs/react';
import { ReactNode } from 'react';

export default function SecondaryLink({ children, href, addClasses }: { children: ReactNode; href: string; addClasses?: string }) {
    return (
        <Link href={href} className={`w-fit rounded border px-2 py-1 font-medium ${addClasses}`}>
            {children}
        </Link>
    );
}
