// public/js copy 2/components/link/normal-link.tsx
import { Link } from '@inertiajs/react';
import { ReactNode } from 'react';

export default function NormalLink({
    children,
    href,
    addClasses,
    title,
}: {
    children: ReactNode;
    href: string;
    addClasses?: string;
    title?: string;
}) {
    return (
        <Link href={href} className={`px-2 py-1 font-medium hover:underline ${addClasses}`} title={title}>
            {children}
        </Link>
    );
}

// resources/js/components/link/NormalLink.vue
<script setup lang="ts">
import { Link } from '@inertiajs/vue3';

type LinkType = {
    href: string;
    addClasses?: string;
    title?: string;
};

const props = defineProps<LinkType>();
</script>

<template>
    <Link :href="href" :title="title" :class="`px-2 py-1 font-medium hover:underline ${addClasses}`">
        <slot />
    </Link>
</template>
