// public/js copy 2/pages/dashboard.tsx
import PrimaryHeading from '@/components/heading/primary-heading';
import EmphasizeText from '@/components/text/emphasize-text';
import NormalText from '@/components/text/normal-text';
import AppLayout from '@/layouts/app-layout';
import { type SharedData } from '@/types';
import { Head, usePage } from '@inertiajs/react';

export default function Page() {
    const { auth } = usePage<SharedData>().props;

    return (
        <>
            <Head title="Dashboard"></Head>
            <AppLayout>
                <div className="flex flex-col gap-4 p-4">
                    <div className="flex items-center gap-2">
                        <PrimaryHeading>Laravel React Starter Kit</PrimaryHeading>
                        <EmphasizeText>lrsk</EmphasizeText>
                    </div>

                    <NormalText>Dashboard</NormalText>
                </div>
            </AppLayout>
        </>
    );
}

// resources/js/pages/dashboard.vue
<script setup lang="ts">
import PrimaryHeading from '@/components/heading/PrimaryHeading.vue';
import EmphasizeText from '@/components/text/EmphasizeText.vue';
import NormalText from '@/components/text/NormalText.vue';
import AppLayout from '@/layouts/AppLayout.vue';
import { Head } from '@inertiajs/vue3';
</script>

<template>
    <Head title="Dashboard"></Head>
    <AppLayout>
        <div class="flex flex-col gap-4 p-4">
            <div class="flex items-center gap-2">
                <PrimaryHeading>Laravel React Starter Kit</PrimaryHeading>
                <EmphasizeText>lrsk</EmphasizeText>
            </div>
            <NormalText>Dashboard</NormalText>
        </div>
    </AppLayout>
</template>
