// resources/js/components/button/NormalButton.vue
<script setup lang="ts">
type ButtonType = {
    addClasses?: string;
    title?: string;
};

const props = defineProps<ButtonType>();
</script>

<template>
    <button type="button" :title="title" :class="`cursor-pointer px-2 py-1 font-medium ${addClasses}`">
        <slot />
    </button>
</template>

// public/js copy 2/components/button/normal-button.tsx
import { MouseEventHandler, ReactNode } from 'react';

export default function NormalButton({
    children,
    addClasses,
    onClick,
}: {
    children: ReactNode;
    addClasses?: string;
    onClick?: MouseEventHandler<HTMLButtonElement>;
}) {
    return (
        <button type="button" className={`cursor-pointer px-2 py-1 font-medium ${addClasses}`} onClick={onClick}>
            {children}
        </button>
    );
}
