// public/js copy 2/components/input/primary-checkbox.tsx
import { ChangeEventHandler } from 'react';

export default function PrimaryCheckbox({
    id,
    label,
    addClasses,
    defaultChecked = false,
    onChange,
}: {
    id: string;
    label: string;
    addClasses?: string;
    defaultChecked?: boolean;
    onChange: ChangeEventHandler<HTMLInputElement>;
}) {
    return (
        <div className="flex flex-wrap items-center gap-2">
            <input id={id} type="checkbox" className={`size-4 ${addClasses}`} defaultChecked={defaultChecked} onChange={onChange} />
            <label htmlFor={id} className="cursor-pointer font-medium">
                {label}
            </label>
        </div>
    );
}

// resources/js/components/input/PrimaryCheckbox.vue
<script setup lang="ts">
type CheckboxType = {
    id: string;
    labelName: string;
    addClasses?: string;
};

const props = defineProps<CheckboxType>();
</script>

<template>
    <div class="flex flex-wrap items-center gap-2">
        <input :id="id" type="checkbox" :class="`size-4 ${addClasses}`" />
        <label :for="id" class="cursor-pointer font-medium">{{ labelName }}</label>
    </div>
</template>
