// public/js copy 2/components/input/primary-input.tsx
import { cn } from '@/lib/utils';
import { ChangeEventHandler } from 'react';

export default function PrimaryInput({
    id,
    label,
    inputType = 'text',
    addClasses,
    placeholder = '**********',
    onChange,
    error,
    defaultValue,
    disabled = false,
}: {
    id: string;
    label: string;
    inputType?: string;
    addClasses?: string;
    placeholder?: string;
    onChange?: ChangeEventHandler<HTMLInputElement>;
    error?: string;
    defaultValue?: string;
    disabled?: boolean;
}) {
    return (
        <div className="flex flex-col gap-1">
            <label htmlFor={id} className="cursor-pointer font-medium">
                {label}
            </label>
            <input
                id={id}
                type={inputType}
                className={`rounded border px-2 py-1 ${addClasses}`}
                placeholder={placeholder}
                onChange={onChange}
                defaultValue={defaultValue}
                disabled={disabled}
            />
            <p
                className={cn('text-red-500', {
                    hidden: !error,
                    block: error,
                })}
            >
                {error}
            </p>
        </div>
    );
}

// resources/js/components/input/PrimaryInput.vue
<script setup lang="ts">
import { cn } from '@/lib/utils.js';

type InputType = {
    id: string;
    labelName: string;
    addClasses?: string;
    inputType?: string;
    placeholder?: string;
    error?: string;
    defaultValue?: string;
    disabled?: boolean;
};

const props = defineProps<InputType>();
</script>

<template>
    <div class="flex flex-col gap-1">
        <label :for="id" class="cursor-pointer font-medium"> {{labelName}} </label>
        <input :id="id" :type="inputType" :class="`rounded border px-2 py-1 ${addClasses}`" :placeholder="placeholder" :disabled="disabled" />
        <p
            :class="
                cn('text-red-500', {
                    hidden: !error,
                    block: error,
                })
            "
        >
            {{ error }}
        </p>
    </div>
</template>
